hosts: 10
switches: 15
seed: 42
k: 2

auto:
  publishers: [9, 0, 3]
  consumers: "random:5"
  content_count: 3
  uri_prefix: "ccnx:/test/experiment"
  consumer_per_content: 2

failure_scenarios:
  strategy: simple
  simple:
    interval: 30
    duration: 10
    count: 2
get_interval: 5
