[project]
name = "cefore-emu"
version = "0.2.0"
description = "Network emulator for Cefore (Content-Centric Networking) deployments"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "mininet>=2.3.0.dev6",
    "networkx>=3.6.1",
    "pyyaml>=6.0",
]

[project.scripts]
ceforeemu = "cli.main:main"

[tool.setuptools.packages.find]
where = ["src"]
