num: 1
hosts: 20
switches: 20
node_per_switch: 6
host_degree_max: 4
host_degree_min: 1
switch_use_all: false
seed: 42
k: 4

puts:
  - host: 2
    uri: "ccnx:/emergency/test"
    file: "./style.css"
    rate: 10
    expiry: 5000
    cache_time: 5000
  - host: 9
    uri: "ccnx:/test/data1"
    file: "./disk IO.png"
  - host: 3
    uri: "ccnx:/emergency/test2"
    file: "./SN7100andSN770.jpg"
    expiry: 5000
    rate: 4
    cache_time: 3000
  - host: 0
    uri: "ccnx:/test/data2"
    file: "./link-audio.sh"

gets:
  - host: 0
    uri: "ccnx:/emergency/test2"
    pipeline: 4
  - host: 6
    uri: "ccnx:/test/data1"
    owner_only: true
  - host: 11
    uri: "ccnx:/emergency/test"
  - host: 16
    uri: "ccnx:/emergency/test"

auto:
  uri: "ccnx:/emergency/test"
  consumers: "random:5"
  content_count: 5

output_dir: "logs"
timestamp: true
no_cli: false

down_interval: 10
down_duration: 20
down_stagger: 5
down_count: 2
get_interval: 5
topo_layout:
bw: h3, s1, 1
bw: h10, s5, 0.5
bridges:
  - switch: s1
    root_ip: "192.168.1.254/24"
    local_routes: "192.168.1.0/24"
    external_routes: "default"
    nat: true
    hosts: [4]
    nat_out: "eno1"
