num: 6
hosts: 15
switches: 30
node_per_switch: 7
host_degree_max: 5
host_degree_min: 3
switch_use_all: false
seed: 42
k: 4

auto:
  publishers: [9, 13, 3]
  consumers: "random:5"
  content_count: 5
  uri_prefix: "ccnx:/test/experiment"
  consumer_per_content: 4

failure_scenarios:
  strategy: simple
  simple:
    interval: 30
    duration: 10
    stagger: 5
    count: 2
get_interval: 5
topo_layout: kamada_kawai
